apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: goldmane
resources:
  - resources.yaml

configMapGenerator:
  - name: goldmane
    literals:
      - config.json={"emitFlows":false}
images:
  - name: docker.io/calico/goldmane
    newTag: v3.31.2@sha256:136bceefc37255c130ada27a333d6bbb62fe3504ebfbf07dd6551f231279007d
