apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: goldmane
  app.kubernetes.io/name: calico
resources:
  - resources.yaml

configMapGenerator:
  - name: goldmane
    literals:
      - config.json={"emitFlows":false}
images:
  - name: docker.io/calico/goldmane
    newTag: v3.31.3@sha256:62316a0ff76734e2026ca79246b02a6578b62ac63f442cbb54ecb55a76f17164
