apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-kube-controllers
resources:
  - ../configurations/prometheus-operator
  - resources.yaml
  - tier-getter.yaml
images:
  - name: docker.io/calico/kube-controllers
    newTag: v3.31.0@sha256:1d3ff1cbb6dc8b0ed4736e92923b0b111705f48803f77a3e5bc54c5b00149e8c
