apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-kube-controllers
resources:
  - ../configurations/prometheus-operator
  - resources.yaml
images:
  - name: docker.io/calico/kube-controllers
    newTag: v3.28.1@sha256:eadb3a25109a5371b7b2dc30d74b2d9b2083eba58abdc034c81f974a48871330
