apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-kube-controllers
resources:
  - ../configurations/prometheus-operator
  - resources.yaml
  - tier-getter.yaml
images:
  - name: docker.io/calico/kube-controllers
    newTag: v3.30.0@sha256:e68a8df468e0adadfad8ada0b6c222ff0a5b0b15861d7a243ff506e1280b3ae2
