apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-node
resources:
  - resources.yaml
  - calico-cni-plugin.yaml
images:
  - name: docker.io/calico/cni
    newTag: v3.30.1@sha256:191f0d9b082070be55b6ce0785817f7cb415097d212ca04c0c1d5448b3fdd062
  - name: docker.io/calico/node
    newTag: v3.30.1@sha256:c1880682c5a0aed91104cdbd809fd8681ff836d797200906b174d4544b2bca75
