apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-node
resources:
  - resources.yaml
  - calico-cni-plugin.yaml
images:
  - name: docker.io/calico/cni
    newTag: v3.28.1@sha256:e486870cfde8189f9ea145148bc353a2c0fca1f445213274023c1d11df69ae19
  - name: docker.io/calico/node
    newTag: v3.28.1@sha256:d8c644a8a3eee06d88825b9a9fec6e7cd3b7c276d7f90afa8685a79fb300e7e3
