apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-node
resources:
  - resources.yaml
  - calico-cni-plugin.yaml
images:
  - name: docker.io/calico/cni
    newTag: v3.29.2@sha256:5c7827667dab3e7ef72682eabc3d0bf8e39c228c67fbf193dfa0a8a8674d300a
  - name: docker.io/calico/node
    newTag: v3.29.2@sha256:97dfd69511ab72c64b4db0636bdf1298b5a7f869ff0296329e0c39dbda4a80b5
