apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-node
resources:
  - resources.yaml
  - calico-cni-plugin.yaml
images:
  - name: docker.io/calico/cni
    newTag: v3.30.4@sha256:807aa264f01c9b9a8c5d26d5ba4fcbc428ab1b8b9798eeac04a64f4930a30c25
  - name: docker.io/calico/node
    newTag: v3.30.4@sha256:362f10b69142fcc654c0ab65a5f371923f9a1d8f7772eac0ff223b9dc67704de
