apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: calico-node
resources:
  - resources.yaml
  - calico-cni-plugin.yaml
images:
  - name: docker.io/calico/cni
    newTag: v3.30.3@sha256:b32ac832411b188a8adc9e31b3e23cbbecd6d63c182a3802e947303f97c2f700
  - name: docker.io/calico/node
    newTag: v3.30.3@sha256:92d8bcca3280cd27b9c98cb6e70c3af10ad6ff8accd288919b04ae0cd6021c2e
