apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: whisker
  app.kubernetes.io/name: calico
resources:
  - resources.yaml
images:
  - name: docker.io/calico/whisker
    newTag: v3.31.3@sha256:3a388b567fff5cc31c64399d4af0fd03d2f4d243ef26e6f6b77a49386dbadeca
  - name: docker.io/calico/whisker-backend
    newTag: v3.31.3@sha256:79d17c50c648d003721e6ca0a5f8eb5b4df1becc25bce272525b0565c06935ef
