apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: whisker
resources:
  - resources.yaml
images:
  - name: docker.io/calico/whisker
    newTag: v3.31.2@sha256:c3ac6b4e8594ab78650a147a6299710e6423795d7a0fa00f1af493113b3d36f5
  - name: docker.io/calico/whisker-backend
    newTag: v3.31.2@sha256:eca1aae793945e296ad6f9f4cb041065e7376db779384668c0dab0002d4e96b4
